// Generated WGSL port of CuNNy veryfast NVL.
// Source: CuNNy-veryfast-NVL.hlsl.
// Generated by scripts/port_cunny_magpie.py from upstream CuNNy Magpie HLSL.
// CuNNy is LGPL-3.0-or-later in the repository license, while the Magpie
// effect headers grant GPL-3.0-or-later terms. SuiSuiView is GPL-3.0-only;
// see THIRD_PARTY_NOTICES.txt for attribution and source availability notes.

struct CuNNyParams {
    source_width: u32,
    source_height: u32,
    output_width: u32,
    output_height: u32,
};

@group(0) @binding(0) var source_tex: texture_2d<f32>;
@group(0) @binding(1) var input0_tex: texture_2d<f32>;
@group(0) @binding(2) var input1_tex: texture_2d<f32>;
@group(0) @binding(3) var input2_tex: texture_2d<f32>;
@group(0) @binding(4) var out0_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(5) var out1_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(6) var out2_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(7) var final_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(8) var<uniform> params: CuNNyParams;

fn clamp_source_coord(coord: vec2<i32>) -> vec2<i32> {
    return clamp(coord, vec2<i32>(0, 0), vec2<i32>(i32(params.source_width) - 1, i32(params.source_height) - 1));
}

fn load_source_luma(coord: vec2<i32>, dx: i32, dy: i32) -> f32 {
    let c = textureLoad(source_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0).rgb;
    return dot(c, vec3<f32>(0.299, 0.587, 0.114));
}
fn load_source_rgb(coord: vec2<i32>, dx: i32, dy: i32) -> vec3<f32> {
    return textureLoad(source_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0).rgb;
}
fn load_input0(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input0_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input1(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input1_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input2(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input2_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }

fn sample_source_rgb_for_output(out_coord: vec2<i32>) -> vec3<f32> {
    let source_scale = vec2<f32>(f32(params.source_width) / f32(params.output_width), f32(params.source_height) / f32(params.output_height));
    let source_pos = (vec2<f32>(out_coord) + vec2<f32>(0.5)) * source_scale - vec2<f32>(0.5);
    let p0f = floor(source_pos);
    let t = source_pos - p0f;
    let p0_base = vec2<i32>(i32(p0f.x), i32(p0f.y));
    let p0 = clamp_source_coord(p0_base);
    let p1 = clamp_source_coord(p0_base + vec2<i32>(1, 1));
    let c00 = textureLoad(source_tex, p0, 0).rgb;
    let c10 = textureLoad(source_tex, vec2<i32>(p1.x, p0.y), 0).rgb;
    let c01 = textureLoad(source_tex, vec2<i32>(p0.x, p1.y), 0).rgb;
    let c11 = textureLoad(source_tex, p1, 0).rgb;
    return mix(mix(c00, c10, t.x), mix(c01, c11, t.x), t.y);
}
fn rgb_to_yuv(rgb: vec3<f32>) -> vec3<f32> { return vec3<f32>(dot(rgb, vec3<f32>(0.299, 0.587, 0.114)), dot(rgb, vec3<f32>(-0.169, -0.331, 0.5)), dot(rgb, vec3<f32>(0.5, -0.419, -0.081))); }
fn yuv_to_rgb(yuv: vec3<f32>) -> vec3<f32> { return vec3<f32>(dot(yuv, vec3<f32>(1.0, -0.00093, 1.401687)), dot(yuv, vec3<f32>(1.0, -0.3437, -0.71417)), dot(yuv, vec3<f32>(1.0, 1.77216, 0.00099))); }
fn write_output_luma_delta(out_coord: vec2<i32>, delta: f32) {
    if (out_coord.x >= i32(params.output_width) || out_coord.y >= i32(params.output_height)) { return; }
    let rgb = sample_source_rgb_for_output(out_coord);
    var yuv = rgb_to_yuv(rgb);
    yuv.x = clamp(yuv.x + delta, 0.0, 1.0);
    textureStore(final_tex, out_coord, vec4<f32>(clamp(yuv_to_rgb(yuv), vec3<f32>(0.0), vec3<f32>(1.0)), 1.0));
}
fn write_output_rgb_delta(out_coord: vec2<i32>, delta: vec3<f32>) {
    if (out_coord.x >= i32(params.output_width) || out_coord.y >= i32(params.output_height)) { return; }
    textureStore(final_tex, out_coord, vec4<f32>(clamp(sample_source_rgb_for_output(out_coord) + delta, vec3<f32>(0.0), vec3<f32>(1.0)), 1.0));
}


// in (1x8)
@compute @workgroup_size(8, 8)
fn cunny_veryfast_nvl_pass_0(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    var r1 = vec4<f32>(0.0);
    let s0_0_0 = load_source_luma(coord, -1, -1);
    let s0_0_1 = load_source_luma(coord, 0, -1);
    let s0_0_2 = load_source_luma(coord, 1, -1);
    let s0_1_0 = load_source_luma(coord, -1, 0);
    let s0_1_1 = load_source_luma(coord, 0, 0);
    let s0_1_2 = load_source_luma(coord, 1, 0);
    let s0_2_0 = load_source_luma(coord, -1, 1);
    let s0_2_1 = load_source_luma(coord, 0, 1);
    let s0_2_2 = load_source_luma(coord, 1, 1);
    r0 += vec4<f32>(-6.888e-02, -6.888e-02, -6.888e-02, -6.888e-02) * s0_0_0;
    r1 += vec4<f32>(1.851e-01, -4.871e-03, -3.070e-02, 1.101e-02) * s0_0_0;
    r0 += vec4<f32>(-1.549e-01, -1.549e-01, -1.549e-01, -1.549e-01) * s0_0_1;
    r1 += vec4<f32>(7.661e-02, -6.060e-02, -9.364e-01, -1.294e-01) * s0_0_1;
    r0 += vec4<f32>(-1.108e-01, -1.108e-01, -1.108e-01, -1.108e-01) * s0_0_2;
    r1 += vec4<f32>(1.214e-01, 9.223e-01, 8.652e-01, 6.247e-01) * s0_0_2;
    r0 += vec4<f32>(-1.392e-01, -1.392e-01, -1.392e-01, -1.392e-01) * s0_1_0;
    r1 += vec4<f32>(3.154e-01, -6.001e-03, 2.772e-02, -1.979e-03) * s0_1_0;
    r0 += vec4<f32>(-5.328e-02, -5.280e-02, -5.328e-02, -5.305e-02) * s0_1_1;
    r1 += vec4<f32>(-5.801e-01, 7.592e-02, 1.241e-01, -1.242e-02) * s0_1_1;
    r0 += vec4<f32>(-6.413e-02, -6.404e-02, -6.413e-02, -6.413e-02) * s0_1_2;
    r1 += vec4<f32>(-1.627e-01, -9.043e-01, -5.475e-02, -1.605e-01) * s0_1_2;
    r0 += vec4<f32>(-1.563e-01, -1.563e-01, -1.563e-01, -1.563e-01) * s0_2_0;
    r1 += vec4<f32>(5.394e-02, 1.075e-02, -8.110e-03, 7.134e-03) * s0_2_0;
    r0 += vec4<f32>(-7.254e-02, -7.254e-02, -7.254e-02, -7.254e-02) * s0_2_1;
    r1 += vec4<f32>(1.842e-01, -1.932e-02, -5.528e-03, -3.423e-02) * s0_2_1;
    r0 += vec4<f32>(-4.679e-02, -4.720e-02, -4.679e-02, -4.725e-02) * s0_2_2;
    r1 += vec4<f32>(2.033e-02, -1.645e-02, 1.672e-02, 2.765e-02) * s0_2_2;
    r0 += vec4<f32>(-6.993e-04, -2.343e-04, -6.993e-04, -3.475e-04);
    r0 = max(r0, vec4<f32>(0.0));
    textureStore(out0_tex, coord, r0);
    r1 += vec4<f32>(3.500e-03, 2.636e-04, 3.864e-04, 4.680e-03);
    r1 = max(r1, vec4<f32>(0.0));
    textureStore(out1_tex, coord, r1);
}

// conv1 (8x8)
@compute @workgroup_size(8, 8)
fn cunny_veryfast_nvl_pass_1(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    var r1 = vec4<f32>(0.0);
    let s0_0_0 = load_input0(coord, -1, -1);
    let s0_0_1 = load_input0(coord, 0, -1);
    let s0_0_2 = load_input0(coord, 1, -1);
    let s0_1_0 = load_input0(coord, -1, 0);
    let s0_1_1 = load_input0(coord, 0, 0);
    let s0_1_2 = load_input0(coord, 1, 0);
    let s0_2_0 = load_input0(coord, -1, 1);
    let s0_2_1 = load_input0(coord, 0, 1);
    let s0_2_2 = load_input0(coord, 1, 1);
    let s1_0_0 = load_input1(coord, -1, -1);
    let s1_0_1 = load_input1(coord, 0, -1);
    let s1_0_2 = load_input1(coord, 1, -1);
    let s1_1_0 = load_input1(coord, -1, 0);
    let s1_1_1 = load_input1(coord, 0, 0);
    let s1_1_2 = load_input1(coord, 1, 0);
    let s1_2_0 = load_input1(coord, -1, 1);
    let s1_2_1 = load_input1(coord, 0, 1);
    let s1_2_2 = load_input1(coord, 1, 1);
    r0 += vec4<f32>(dot(s0_0_0, vec4<f32>(9.942e-02, 5.382e-02, 2.066e-01, -4.982e-03)), dot(s0_0_0, vec4<f32>(9.942e-02, 5.109e-02, 2.066e-01, -6.896e-03)), dot(s0_0_0, vec4<f32>(9.942e-02, 4.971e-02, 2.066e-01, -8.240e-03)), dot(s0_0_0, vec4<f32>(9.942e-02, 5.303e-02, 2.066e-01, -5.609e-03)));
    r1 += vec4<f32>(dot(s0_0_0, vec4<f32>(3.222e-02, -2.166e-01, -1.292e-02, -2.242e-01)), dot(s0_0_0, vec4<f32>(3.222e-02, -2.166e-01, -1.292e-02, -2.242e-01)), dot(s0_0_0, vec4<f32>(3.222e-02, -2.159e-01, -1.292e-02, -2.236e-01)), dot(s0_0_0, vec4<f32>(3.222e-02, -2.161e-01, -1.292e-02, -2.239e-01)));
    r0 += vec4<f32>(dot(s0_0_1, vec4<f32>(1.187e-01, 7.311e-02, -1.313e-01, 8.349e-02)), dot(s0_0_1, vec4<f32>(1.187e-01, 7.000e-02, -1.313e-01, 8.108e-02)), dot(s0_0_1, vec4<f32>(1.187e-01, 6.898e-02, -1.313e-01, 8.026e-02)), dot(s0_0_1, vec4<f32>(1.187e-01, 7.144e-02, -1.313e-01, 8.194e-02)));
    r1 += vec4<f32>(dot(s0_0_1, vec4<f32>(-1.635e-02, -2.273e-01, -3.197e-05, 1.562e-01)), dot(s0_0_1, vec4<f32>(-1.635e-02, -2.271e-01, -3.197e-05, 1.563e-01)), dot(s0_0_1, vec4<f32>(-1.635e-02, -2.268e-01, -3.197e-05, 1.564e-01)), dot(s0_0_1, vec4<f32>(-1.635e-02, -2.269e-01, -3.197e-05, 1.565e-01)));
    r0 += vec4<f32>(dot(s0_0_2, vec4<f32>(9.596e-02, -1.092e-02, -1.288e-01, -2.879e-01)), dot(s0_0_2, vec4<f32>(9.596e-02, -1.260e-02, -1.288e-01, -2.891e-01)), dot(s0_0_2, vec4<f32>(9.596e-02, -1.328e-02, -1.288e-01, -2.895e-01)), dot(s0_0_2, vec4<f32>(9.596e-02, -1.199e-02, -1.288e-01, -2.890e-01)));
    r1 += vec4<f32>(dot(s0_0_2, vec4<f32>(5.212e-02, 6.973e-03, 9.334e-02, -8.878e-02)), dot(s0_0_2, vec4<f32>(5.212e-02, 7.001e-03, 9.334e-02, -8.867e-02)), dot(s0_0_2, vec4<f32>(5.212e-02, 7.464e-03, 9.334e-02, -8.852e-02)), dot(s0_0_2, vec4<f32>(5.212e-02, 7.172e-03, 9.334e-02, -8.854e-02)));
    r0 += vec4<f32>(dot(s0_1_0, vec4<f32>(-3.400e-02, -9.487e-02, -4.091e-03, 4.897e-03)), dot(s0_1_0, vec4<f32>(-3.400e-02, -9.820e-02, -4.091e-03, 2.427e-03)), dot(s0_1_0, vec4<f32>(-3.400e-02, -9.909e-02, -4.091e-03, 1.496e-03)), dot(s0_1_0, vec4<f32>(-3.400e-02, -9.531e-02, -4.091e-03, 4.505e-03)));
    r1 += vec4<f32>(dot(s0_1_0, vec4<f32>(5.865e-02, -9.595e-03, -7.642e-02, -2.204e-01)), dot(s0_1_0, vec4<f32>(5.865e-02, -9.721e-03, -7.642e-02, -2.205e-01)), dot(s0_1_0, vec4<f32>(5.865e-02, -9.107e-03, -7.642e-02, -2.200e-01)), dot(s0_1_0, vec4<f32>(5.865e-02, -9.533e-03, -7.642e-02, -2.203e-01)));
    r0 += vec4<f32>(dot(s0_1_1, vec4<f32>(-8.614e-02, -3.672e-02, -1.740e-01, 1.696e-01)), dot(s0_1_1, vec4<f32>(-8.614e-02, -4.032e-02, -1.740e-01, 1.666e-01)), dot(s0_1_1, vec4<f32>(-8.614e-02, -4.105e-02, -1.740e-01, 1.660e-01)), dot(s0_1_1, vec4<f32>(-8.614e-02, -3.769e-02, -1.740e-01, 1.687e-01)));
    r1 += vec4<f32>(dot(s0_1_1, vec4<f32>(2.293e-01, 1.890e-01, -4.597e-03, 1.807e-01)), dot(s0_1_1, vec4<f32>(2.293e-01, 1.890e-01, -4.597e-03, 1.807e-01)), dot(s0_1_1, vec4<f32>(2.293e-01, 1.890e-01, -4.597e-03, 1.805e-01)), dot(s0_1_1, vec4<f32>(2.293e-01, 1.891e-01, -4.597e-03, 1.809e-01)));
    r0 += vec4<f32>(dot(s0_1_2, vec4<f32>(-2.350e-02, -2.455e-01, -3.775e-02, 1.058e-01)), dot(s0_1_2, vec4<f32>(-2.350e-02, -2.487e-01, -3.775e-02, 1.032e-01)), dot(s0_1_2, vec4<f32>(-2.350e-02, -2.493e-01, -3.775e-02, 1.026e-01)), dot(s0_1_2, vec4<f32>(-2.350e-02, -2.465e-01, -3.775e-02, 1.049e-01)));
    r1 += vec4<f32>(dot(s0_1_2, vec4<f32>(1.597e-01, 8.256e-02, -2.294e-01, -3.658e-02)), dot(s0_1_2, vec4<f32>(1.597e-01, 8.257e-02, -2.294e-01, -3.651e-02)), dot(s0_1_2, vec4<f32>(1.597e-01, 8.261e-02, -2.294e-01, -3.665e-02)), dot(s0_1_2, vec4<f32>(1.597e-01, 8.276e-02, -2.294e-01, -3.637e-02)));
    r0 += vec4<f32>(dot(s0_2_0, vec4<f32>(-6.540e-02, 6.741e-02, -2.575e-02, -7.069e-02)), dot(s0_2_0, vec4<f32>(-6.540e-02, 6.394e-02, -2.575e-02, -7.322e-02)), dot(s0_2_0, vec4<f32>(-6.540e-02, 6.310e-02, -2.575e-02, -7.416e-02)), dot(s0_2_0, vec4<f32>(-6.540e-02, 6.688e-02, -2.575e-02, -7.109e-02)));
    r1 += vec4<f32>(dot(s0_2_0, vec4<f32>(9.200e-02, 1.466e-01, 1.094e-01, -5.608e-02)), dot(s0_2_0, vec4<f32>(9.200e-02, 1.465e-01, 1.094e-01, -5.613e-02)), dot(s0_2_0, vec4<f32>(9.200e-02, 1.472e-01, 1.094e-01, -5.557e-02)), dot(s0_2_0, vec4<f32>(9.200e-02, 1.467e-01, 1.094e-01, -5.598e-02)));
    r0 += vec4<f32>(dot(s0_2_1, vec4<f32>(6.093e-02, 1.594e-01, -2.519e-02, -6.842e-02)), dot(s0_2_1, vec4<f32>(6.093e-02, 1.557e-01, -2.519e-02, -7.120e-02)), dot(s0_2_1, vec4<f32>(6.093e-02, 1.551e-01, -2.519e-02, -7.189e-02)), dot(s0_2_1, vec4<f32>(6.093e-02, 1.585e-01, -2.519e-02, -6.918e-02)));
    r1 += vec4<f32>(dot(s0_2_1, vec4<f32>(-1.109e-01, -1.036e-01, 1.746e-01, 1.227e-01)), dot(s0_2_1, vec4<f32>(-1.109e-01, -1.035e-01, 1.746e-01, 1.228e-01)), dot(s0_2_1, vec4<f32>(-1.109e-01, -1.031e-01, 1.746e-01, 1.231e-01)), dot(s0_2_1, vec4<f32>(-1.109e-01, -1.034e-01, 1.746e-01, 1.229e-01)));
    r0 += vec4<f32>(dot(s0_2_2, vec4<f32>(-1.138e-01, 6.757e-02, -2.323e-02, -1.918e-02)), dot(s0_2_2, vec4<f32>(-1.138e-01, 6.418e-02, -2.323e-02, -2.165e-02)), dot(s0_2_2, vec4<f32>(-1.138e-01, 6.360e-02, -2.323e-02, -2.230e-02)), dot(s0_2_2, vec4<f32>(-1.138e-01, 6.645e-02, -2.323e-02, -2.008e-02)));
    r1 += vec4<f32>(dot(s0_2_2, vec4<f32>(-2.404e-01, 4.725e-02, -1.532e-01, 2.064e-02)), dot(s0_2_2, vec4<f32>(-2.404e-01, 4.727e-02, -1.532e-01, 2.071e-02)), dot(s0_2_2, vec4<f32>(-2.404e-01, 4.769e-02, -1.532e-01, 2.103e-02)), dot(s0_2_2, vec4<f32>(-2.404e-01, 4.736e-02, -1.532e-01, 2.077e-02)));
    r0 += vec4<f32>(dot(s1_0_0, vec4<f32>(1.503e-02, -3.193e-01, 1.723e-01, -1.645e-01)), dot(s1_0_0, vec4<f32>(-1.960e-02, -9.443e-02, 3.899e-02, -3.447e-01)), dot(s1_0_0, vec4<f32>(1.255e-02, 1.131e-01, -5.871e-02, -2.373e-02)), dot(s1_0_0, vec4<f32>(-1.863e-01, 1.684e-01, -5.609e-02, 8.718e-03)));
    r1 += vec4<f32>(dot(s1_0_0, vec4<f32>(-3.186e-02, -6.872e-02, -2.046e-01, 1.215e-01)), dot(s1_0_0, vec4<f32>(-1.823e-02, 7.742e-02, 4.693e-02, -1.503e-03)), dot(s1_0_0, vec4<f32>(-3.665e-02, 4.445e-02, -2.017e-01, 3.898e-01)), dot(s1_0_0, vec4<f32>(1.011e-02, -7.129e-01, 3.924e-02, 1.867e-01)));
    r0 += vec4<f32>(dot(s1_0_1, vec4<f32>(-8.506e-03, -7.498e-02, -4.212e-02, 1.237e-01)), dot(s1_0_1, vec4<f32>(1.071e-01, -4.339e-03, 1.029e-01, -1.978e-01)), dot(s1_0_1, vec4<f32>(-7.005e-02, -3.249e-02, -1.584e-02, -1.163e-01)), dot(s1_0_1, vec4<f32>(-3.235e-01, -7.349e-02, 9.638e-02, 2.892e-01)));
    r1 += vec4<f32>(dot(s1_0_1, vec4<f32>(-4.856e-03, -2.871e-02, 3.109e-02, -7.959e-02)), dot(s1_0_1, vec4<f32>(-1.440e-01, -1.242e-02, -1.667e-01, 1.860e-01)), dot(s1_0_1, vec4<f32>(-4.110e-01, 5.001e-02, -8.709e-02, 1.454e-01)), dot(s1_0_1, vec4<f32>(6.669e-02, -1.102e-01, -3.059e-02, 5.388e-02)));
    r0 += vec4<f32>(dot(s1_0_2, vec4<f32>(-1.608e-02, 1.295e-03, 1.273e-02, 2.145e-03)), dot(s1_0_2, vec4<f32>(8.333e-01, -9.936e-02, -6.233e-02, -7.090e-02)), dot(s1_0_2, vec4<f32>(-1.685e-01, 8.806e-02, -1.304e-01, 9.691e-02)), dot(s1_0_2, vec4<f32>(2.728e-01, 5.244e-02, 1.520e-01, -2.036e-01)));
    r1 += vec4<f32>(dot(s1_0_2, vec4<f32>(-3.460e-01, -6.200e-02, -7.300e-02, 1.798e-01)), dot(s1_0_2, vec4<f32>(-2.572e-01, 9.984e-02, -7.132e-02, -5.185e-02)), dot(s1_0_2, vec4<f32>(-6.152e-01, -1.518e-02, -2.681e-02, 1.485e-01)), dot(s1_0_2, vec4<f32>(-4.448e-01, -5.071e-02, 5.605e-02, 1.150e-01)));
    r0 += vec4<f32>(dot(s1_1_0, vec4<f32>(5.383e-02, 3.838e-01, 5.291e-01, 1.761e-01)), dot(s1_1_0, vec4<f32>(3.283e-02, -4.281e-02, -5.838e-02, 7.232e-01)), dot(s1_1_0, vec4<f32>(-6.840e-05, 1.880e-01, 1.362e-01, -9.092e-02)), dot(s1_1_0, vec4<f32>(2.703e-01, -1.801e+00, -3.232e-01, 1.104e+00)));
    r1 += vec4<f32>(dot(s1_1_0, vec4<f32>(-6.027e-02, 3.687e-01, -1.576e-01, 7.848e-02)), dot(s1_1_0, vec4<f32>(2.765e-02, 5.033e-01, 1.116e-01, -8.011e-01)), dot(s1_1_0, vec4<f32>(4.413e-02, -8.089e-03, 2.135e-02, -2.960e-02)), dot(s1_1_0, vec4<f32>(-3.890e-02, -3.840e-01, 8.044e-03, 1.646e-01)));
    r0 += vec4<f32>(dot(s1_1_1, vec4<f32>(2.452e-02, 1.646e-01, -2.881e-01, -1.370e-01)), dot(s1_1_1, vec4<f32>(-2.222e-01, 2.188e-01, -7.908e+00, -5.533e-01)), dot(s1_1_1, vec4<f32>(2.485e-01, 6.573e-02, 2.163e-01, 5.083e-01)), dot(s1_1_1, vec4<f32>(-7.636e-01, 7.168e-01, -8.756e-01, -5.938e-01)));
    r1 += vec4<f32>(dot(s1_1_1, vec4<f32>(7.733e-02, 5.625e-01, 3.037e-01, -1.593e-03)), dot(s1_1_1, vec4<f32>(2.378e-01, -2.318e+00, 2.329e-01, -8.457e-01)), dot(s1_1_1, vec4<f32>(5.796e-01, -5.621e-01, -3.662e-01, 4.032e-01)), dot(s1_1_1, vec4<f32>(-1.646e-01, -2.848e-01, -8.920e-01, 7.062e-01)));
    r0 += vec4<f32>(dot(s1_1_2, vec4<f32>(1.363e-02, 5.945e-02, -4.211e-02, -7.523e-03)), dot(s1_1_2, vec4<f32>(5.876e-01, -2.588e-01, 1.333e-01, 1.426e-01)), dot(s1_1_2, vec4<f32>(-1.549e-01, 3.897e-01, -2.864e-01, -3.193e-01)), dot(s1_1_2, vec4<f32>(-6.083e-01, 2.221e-01, 1.493e-01, -1.892e-01)));
    r1 += vec4<f32>(dot(s1_1_2, vec4<f32>(1.107e-01, -1.833e-02, 2.071e-02, -7.837e-02)), dot(s1_1_2, vec4<f32>(-3.803e-01, -3.057e-02, -9.067e-02, 7.217e-02)), dot(s1_1_2, vec4<f32>(6.230e-01, -1.802e-01, -5.696e-02, -1.157e-01)), dot(s1_1_2, vec4<f32>(7.461e-01, 7.218e-02, -3.686e-01, -1.809e-01)));
    r0 += vec4<f32>(dot(s1_2_0, vec4<f32>(-4.004e-03, 3.537e-02, 1.440e-01, -9.021e-02)), dot(s1_2_0, vec4<f32>(-2.873e-02, 1.193e-01, -2.732e-02, -2.910e-01)), dot(s1_2_0, vec4<f32>(-1.248e-02, -6.275e-03, 2.292e-01, 3.163e-02)), dot(s1_2_0, vec4<f32>(-7.481e-02, -2.630e-01, -7.393e-01, 4.677e-01)));
    r1 += vec4<f32>(dot(s1_2_0, vec4<f32>(3.184e-02, -5.840e-01, -5.488e-01, 4.810e-02)), dot(s1_2_0, vec4<f32>(5.904e-03, -1.636e-01, 2.233e-02, 6.687e-01)), dot(s1_2_0, vec4<f32>(-4.461e-02, -3.201e-01, -4.980e-02, -2.496e-01)), dot(s1_2_0, vec4<f32>(1.023e-01, 3.096e-01, 2.377e-01, -4.718e-01)));
    r0 += vec4<f32>(dot(s1_2_1, vec4<f32>(-4.627e-02, -5.563e-03, -6.761e-02, 7.838e-02)), dot(s1_2_1, vec4<f32>(1.233e-01, 4.923e-02, -7.338e-03, -2.902e-01)), dot(s1_2_1, vec4<f32>(-9.253e-02, -8.105e-01, 7.265e-02, -7.430e-01)), dot(s1_2_1, vec4<f32>(3.282e-02, 9.086e-02, -1.942e+00, 4.542e-02)));
    r1 += vec4<f32>(dot(s1_2_1, vec4<f32>(-2.612e-02, -5.314e-02, 4.281e-01, 3.565e-02)), dot(s1_2_1, vec4<f32>(1.045e-02, -2.232e-01, -2.744e-01, 1.066e+00)), dot(s1_2_1, vec4<f32>(-3.740e-01, 3.154e-01, 4.056e-01, -4.736e-01)), dot(s1_2_1, vec4<f32>(8.964e-02, -3.018e-01, -1.573e-02, -6.388e-01)));
    r0 += vec4<f32>(dot(s1_2_2, vec4<f32>(6.906e-03, 1.331e-02, -1.265e-02, 6.216e-03)), dot(s1_2_2, vec4<f32>(-9.988e-02, 6.250e-02, -1.620e-02, 5.887e-03)), dot(s1_2_2, vec4<f32>(-7.005e-02, -7.090e-01, -5.879e-01, 8.379e-01)), dot(s1_2_2, vec4<f32>(-3.736e-03, 1.490e-02, 1.166e-01, -3.583e-02)));
    r1 += vec4<f32>(dot(s1_2_2, vec4<f32>(2.457e-02, 1.647e-03, 4.474e-02, -1.653e-01)), dot(s1_2_2, vec4<f32>(1.454e-02, -6.089e-02, -4.131e-01, 1.043e-02)), dot(s1_2_2, vec4<f32>(-5.554e-02, 3.495e-02, 9.189e-02, -5.773e-02)), dot(s1_2_2, vec4<f32>(-4.939e-01, -9.100e-02, 2.397e-01, 1.314e-01)));
    r0 = max(r0, vec4<f32>(0.0));
    textureStore(out0_tex, coord, r0);
    r1 = max(r1, vec4<f32>(0.0));
    textureStore(out1_tex, coord, r1);
}

// conv2 (8x4)
@compute @workgroup_size(8, 8)
fn cunny_veryfast_nvl_pass_2(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    let s0_0_0 = load_input0(coord, -1, -1);
    let s0_0_1 = load_input0(coord, 0, -1);
    let s0_0_2 = load_input0(coord, 1, -1);
    let s0_1_0 = load_input0(coord, -1, 0);
    let s0_1_1 = load_input0(coord, 0, 0);
    let s0_1_2 = load_input0(coord, 1, 0);
    let s0_2_0 = load_input0(coord, -1, 1);
    let s0_2_1 = load_input0(coord, 0, 1);
    let s0_2_2 = load_input0(coord, 1, 1);
    let s1_0_0 = load_input1(coord, -1, -1);
    let s1_0_1 = load_input1(coord, 0, -1);
    let s1_0_2 = load_input1(coord, 1, -1);
    let s1_1_0 = load_input1(coord, -1, 0);
    let s1_1_1 = load_input1(coord, 0, 0);
    let s1_1_2 = load_input1(coord, 1, 0);
    let s1_2_0 = load_input1(coord, -1, 1);
    let s1_2_1 = load_input1(coord, 0, 1);
    let s1_2_2 = load_input1(coord, 1, 1);
    r0 += vec4<f32>(dot(s0_0_0, vec4<f32>(4.652e-02, 3.834e-03, -1.450e-01, -3.711e-04)), dot(s0_0_0, vec4<f32>(2.118e-02, 1.011e-02, -1.499e-01, 2.741e-02)), dot(s0_0_0, vec4<f32>(1.777e-02, -6.713e-02, 2.302e-03, -3.458e-02)), dot(s0_0_0, vec4<f32>(-2.906e-02, 1.085e-02, 2.583e-02, 3.259e-02)));
    r0 += vec4<f32>(dot(s0_0_1, vec4<f32>(-2.569e-04, 5.387e-02, 5.662e-03, -3.874e-02)), dot(s0_0_1, vec4<f32>(4.004e-02, 6.909e-02, -2.999e-02, -6.909e-02)), dot(s0_0_1, vec4<f32>(7.850e-02, -8.329e-02, -1.608e-01, 6.379e-02)), dot(s0_0_1, vec4<f32>(-2.020e-01, -3.478e-02, -8.773e-03, 2.815e-02)));
    r0 += vec4<f32>(dot(s0_0_2, vec4<f32>(-2.328e-02, -9.687e-03, -1.682e-02, 2.338e-02)), dot(s0_0_2, vec4<f32>(-3.024e-02, 3.121e-02, -2.241e-02, 1.218e-03)), dot(s0_0_2, vec4<f32>(2.104e-01, 9.264e-05, 3.162e-02, 3.072e-03)), dot(s0_0_2, vec4<f32>(-1.535e-01, -2.195e-02, -7.546e-02, 3.387e-02)));
    r0 += vec4<f32>(dot(s0_1_0, vec4<f32>(3.568e-02, 3.682e-01, -1.668e-01, -1.191e+00)), dot(s0_1_0, vec4<f32>(1.605e-02, 3.291e-01, -9.767e-03, -1.490e-01)), dot(s0_1_0, vec4<f32>(-3.021e-02, 1.265e-01, 3.429e-02, -1.627e-01)), dot(s0_1_0, vec4<f32>(1.744e-01, -1.594e-02, -6.392e-01, -2.411e-02)));
    r0 += vec4<f32>(dot(s0_1_1, vec4<f32>(1.743e-01, -2.777e-01, 7.803e-02, -2.023e-01)), dot(s0_1_1, vec4<f32>(2.075e-02, -2.362e-02, -1.213e-01, -3.512e-01)), dot(s0_1_1, vec4<f32>(6.223e-02, 2.783e-01, -2.707e-02, 1.473e-02)), dot(s0_1_1, vec4<f32>(4.957e-01, 1.053e-01, -9.065e-02, -5.604e-01)));
    r0 += vec4<f32>(dot(s0_1_2, vec4<f32>(1.044e-01, 5.310e-02, -3.514e-02, -5.674e-02)), dot(s0_1_2, vec4<f32>(1.391e-01, -2.680e-02, 2.059e-02, -3.518e-02)), dot(s0_1_2, vec4<f32>(6.655e-01, 1.876e-02, 3.658e-02, 3.321e-03)), dot(s0_1_2, vec4<f32>(1.817e-01, 1.084e-01, -5.265e-04, -6.615e-02)));
    r0 += vec4<f32>(dot(s0_2_0, vec4<f32>(-8.915e-02, 7.012e-01, -4.912e-01, -4.359e-02)), dot(s0_2_0, vec4<f32>(6.793e-03, 6.113e-01, -2.744e-01, 8.894e-02)), dot(s0_2_0, vec4<f32>(2.528e-02, 4.309e-02, 1.652e-02, 3.203e-02)), dot(s0_2_0, vec4<f32>(-9.072e-02, 8.535e-01, 2.939e-01, -6.715e-02)));
    r0 += vec4<f32>(dot(s0_2_1, vec4<f32>(-5.987e-01, -4.131e-01, 2.901e-02, -5.164e-02)), dot(s0_2_1, vec4<f32>(-4.502e-01, 5.164e-02, -6.327e-02, -1.558e-01)), dot(s0_2_1, vec4<f32>(-5.588e-02, -3.366e-02, 7.825e-03, -8.130e-02)), dot(s0_2_1, vec4<f32>(-8.027e-01, 3.236e-02, -5.461e-02, -9.202e-01)));
    r0 += vec4<f32>(dot(s0_2_2, vec4<f32>(2.355e-01, -6.700e-03, -1.610e-02, -2.354e-02)), dot(s0_2_2, vec4<f32>(3.057e-01, -4.599e-02, -8.160e-03, -2.492e-02)), dot(s0_2_2, vec4<f32>(1.048e-01, -1.574e-03, 2.584e-03, 6.279e-04)), dot(s0_2_2, vec4<f32>(4.131e-01, -1.018e-01, 7.788e-02, -3.643e-02)));
    r0 += vec4<f32>(dot(s1_0_0, vec4<f32>(2.251e-02, -4.309e-02, 6.238e-02, -2.524e-02)), dot(s1_0_0, vec4<f32>(1.874e-02, 1.593e-02, 5.182e-02, -7.151e-02)), dot(s1_0_0, vec4<f32>(-4.000e-02, -3.397e-02, 9.493e-02, 1.067e-01)), dot(s1_0_0, vec4<f32>(1.636e-01, -8.663e-03, -2.822e-01, -1.929e-01)));
    r0 += vec4<f32>(dot(s1_0_1, vec4<f32>(8.030e-02, 6.406e-02, -8.327e-02, 6.226e-02)), dot(s1_0_1, vec4<f32>(3.430e-02, -2.345e-02, 3.853e-02, 4.112e-02)), dot(s1_0_1, vec4<f32>(3.593e-02, 2.400e-02, -1.762e-01, -3.545e-01)), dot(s1_0_1, vec4<f32>(2.046e-01, -1.655e-02, -3.678e-01, -1.427e-02)));
    r0 += vec4<f32>(dot(s1_0_2, vec4<f32>(-1.224e-02, -3.504e-02, 3.428e-02, 6.182e-03)), dot(s1_0_2, vec4<f32>(4.359e-02, 4.967e-03, 1.307e-02, 6.040e-02)), dot(s1_0_2, vec4<f32>(-4.925e-02, -1.392e-02, 4.165e-02, 3.111e-02)), dot(s1_0_2, vec4<f32>(1.750e-02, -6.436e-03, -1.347e-01, 2.771e-02)));
    r0 += vec4<f32>(dot(s1_1_0, vec4<f32>(4.014e-01, -1.155e-01, -1.450e-01, -1.958e-01)), dot(s1_1_0, vec4<f32>(1.840e-01, 5.106e-02, -9.890e-02, -1.578e-01)), dot(s1_1_0, vec4<f32>(9.982e-02, -9.400e-02, -8.620e-02, -1.347e-01)), dot(s1_1_0, vec4<f32>(-3.458e-02, 1.850e-01, 1.938e-01, 8.244e-02)));
    r0 += vec4<f32>(dot(s1_1_1, vec4<f32>(-2.377e-01, 2.454e-01, 2.803e-01, -2.529e-01)), dot(s1_1_1, vec4<f32>(2.027e-01, -1.255e-01, 2.202e-01, -2.555e-01)), dot(s1_1_1, vec4<f32>(1.880e-01, 2.336e-01, 1.830e-01, -4.357e-02)), dot(s1_1_1, vec4<f32>(-1.763e-01, -2.347e-01, 5.304e-01, -1.778e-01)));
    r0 += vec4<f32>(dot(s1_1_2, vec4<f32>(3.724e-02, -1.265e-01, 4.700e-02, 4.040e-02)), dot(s1_1_2, vec4<f32>(-4.195e-03, 2.753e-02, 8.615e-02, -5.118e-02)), dot(s1_1_2, vec4<f32>(6.167e-02, -1.161e-01, -9.542e-03, -1.865e-02)), dot(s1_1_2, vec4<f32>(7.180e-02, -2.013e-03, 6.567e-02, -2.315e-02)));
    r0 += vec4<f32>(dot(s1_2_0, vec4<f32>(3.271e-01, 5.761e-01, -7.564e-02, -1.690e-01)), dot(s1_2_0, vec4<f32>(-1.629e-02, 5.176e-01, -3.276e-03, -1.606e-01)), dot(s1_2_0, vec4<f32>(8.649e-05, 5.844e-02, -1.355e-02, -1.097e-02)), dot(s1_2_0, vec4<f32>(8.125e-02, 3.115e-01, 6.944e-02, -3.740e-01)));
    r0 += vec4<f32>(dot(s1_2_1, vec4<f32>(-1.664e-01, 2.339e-01, -3.451e-02, -1.812e-01)), dot(s1_2_1, vec4<f32>(2.162e-02, 4.658e-01, -5.517e-02, -1.304e-01)), dot(s1_2_1, vec4<f32>(1.268e-02, 1.592e-02, -4.687e-04, -1.155e-02)), dot(s1_2_1, vec4<f32>(2.446e-01, 5.684e-01, -3.574e-02, -2.764e-01)));
    r0 += vec4<f32>(dot(s1_2_2, vec4<f32>(1.367e-02, 1.960e-02, 1.116e-01, -3.034e-02)), dot(s1_2_2, vec4<f32>(-1.998e-02, 9.689e-02, 4.511e-02, -6.239e-02)), dot(s1_2_2, vec4<f32>(-4.510e-02, -3.869e-02, 1.789e-02, -3.647e-03)), dot(s1_2_2, vec4<f32>(-6.963e-02, 9.008e-02, 1.987e-01, -1.205e-01)));
    r0 = max(r0, vec4<f32>(0.0));
    textureStore(out0_tex, coord, r0);
}

// out-shuffle (4x4)
@compute @workgroup_size(8, 8)
fn cunny_veryfast_nvl_pass_3(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    let s0_0_0 = load_input0(coord, -1, -1);
    let s0_0_1 = load_input0(coord, 0, -1);
    let s0_0_2 = load_input0(coord, 1, -1);
    let s0_1_0 = load_input0(coord, -1, 0);
    let s0_1_1 = load_input0(coord, 0, 0);
    let s0_1_2 = load_input0(coord, 1, 0);
    let s0_2_0 = load_input0(coord, -1, 1);
    let s0_2_1 = load_input0(coord, 0, 1);
    let s0_2_2 = load_input0(coord, 1, 1);
    r0 += vec4<f32>(dot(s0_0_0, vec4<f32>(-8.466e-03, 4.039e-02, -9.043e-02, 2.522e-02)), dot(s0_0_0, vec4<f32>(8.423e-03, 1.243e-02, -4.385e-02, -1.250e-02)), dot(s0_0_0, vec4<f32>(-1.341e-02, 3.053e-03, 1.099e-02, 1.207e-02)), dot(s0_0_0, vec4<f32>(8.400e-03, 2.236e-02, -4.289e-03, -6.843e-04)));
    r0 += vec4<f32>(dot(s0_0_1, vec4<f32>(2.039e-02, 1.700e-01, -2.046e-02, 4.650e-02)), dot(s0_0_1, vec4<f32>(2.086e-02, 1.294e-01, -6.568e-02, 7.837e-02)), dot(s0_0_1, vec4<f32>(7.522e-03, -2.264e-02, -3.262e-03, -1.792e-03)), dot(s0_0_1, vec4<f32>(-3.699e-02, 4.882e-03, 1.502e-02, 6.150e-03)));
    r0 += vec4<f32>(dot(s0_0_2, vec4<f32>(1.362e-03, 1.193e-02, -6.344e-03, -2.810e-02)), dot(s0_0_2, vec4<f32>(-4.553e-03, 6.665e-02, -1.285e-03, -9.490e-03)), dot(s0_0_2, vec4<f32>(-5.095e-03, 9.653e-03, 6.389e-04, 2.764e-03)), dot(s0_0_2, vec4<f32>(-1.786e-02, -1.117e-02, -1.254e-04, 1.519e-02)));
    r0 += vec4<f32>(dot(s0_1_0, vec4<f32>(6.046e-02, -2.222e-01, 2.124e-01, 1.470e-01)), dot(s0_1_0, vec4<f32>(-5.579e-02, 6.714e-02, 2.800e-02, 2.230e-03)), dot(s0_1_0, vec4<f32>(4.086e-02, 1.642e-01, -2.271e-01, -2.017e-01)), dot(s0_1_0, vec4<f32>(-2.594e-02, 1.251e-02, -1.145e-01, 2.901e-02)));
    r0 += vec4<f32>(dot(s0_1_1, vec4<f32>(-6.934e-01, -1.182e-01, -1.213e-01, 3.785e-01)), dot(s0_1_1, vec4<f32>(6.074e-01, -1.321e+00, 1.228e-01, 3.936e-01)), dot(s0_1_1, vec4<f32>(-3.916e-01, 5.566e-01, -2.879e-02, -3.096e-01)), dot(s0_1_1, vec4<f32>(3.975e-01, 3.135e-02, -1.585e-01, -5.809e-01)));
    r0 += vec4<f32>(dot(s0_1_2, vec4<f32>(5.465e-02, 2.840e-02, 8.899e-03, -3.886e-02)), dot(s0_1_2, vec4<f32>(1.837e-02, 1.509e-01, -6.614e-02, 5.009e-02)), dot(s0_1_2, vec4<f32>(6.128e-03, -1.450e-02, -1.062e-02, 1.448e-02)), dot(s0_1_2, vec4<f32>(-2.014e-02, 1.985e-01, -8.987e-03, 3.161e-02)));
    r0 += vec4<f32>(dot(s0_2_0, vec4<f32>(-1.064e-02, -6.714e-02, 2.007e-01, 3.036e-03)), dot(s0_2_0, vec4<f32>(1.822e-02, -4.944e-02, 2.301e-02, 1.199e-02)), dot(s0_2_0, vec4<f32>(1.365e-03, -1.042e-01, 5.776e-01, 1.776e-02)), dot(s0_2_0, vec4<f32>(-1.041e-02, -3.769e-02, 1.213e-01, 4.685e-03)));
    r0 += vec4<f32>(dot(s0_2_1, vec4<f32>(5.676e-02, 1.734e-02, -1.548e-01, -3.189e-02)), dot(s0_2_1, vec4<f32>(9.702e-03, 2.728e-02, 9.495e-02, -2.570e-02)), dot(s0_2_1, vec4<f32>(-2.397e-01, 8.738e-02, -2.007e-01, 6.957e-02)), dot(s0_2_1, vec4<f32>(2.686e-01, -3.604e-01, 3.917e-01, 7.940e-02)));
    r0 += vec4<f32>(dot(s0_2_2, vec4<f32>(-1.035e-02, 2.739e-02, -5.462e-03, 8.643e-03)), dot(s0_2_2, vec4<f32>(-2.055e-04, 1.148e-02, -7.788e-02, -7.950e-03)), dot(s0_2_2, vec4<f32>(3.797e-02, -1.547e-03, 4.641e-03, -8.491e-03)), dot(s0_2_2, vec4<f32>(3.525e-02, 3.837e-02, -1.392e-01, -1.800e-02)));
    r0 += vec4<f32>(-5.434e-06, 1.445e-05, -9.457e-05, -3.159e-05);
    let base = coord * vec2<i32>(2, 2);
    write_output_luma_delta(base + vec2<i32>(0, 0), r0.x);
    write_output_luma_delta(base + vec2<i32>(1, 0), r0.y);
    write_output_luma_delta(base + vec2<i32>(0, 1), r0.z);
    write_output_luma_delta(base + vec2<i32>(1, 1), r0.w);
}
