// Generated WGSL port of CuNNy veryfast SOFT.

// Source: CuNNy-veryfast-SOFT.glsl.

// Generated by scripts/port_cunny_mpv.py from upstream CuNNy mpv GLSL.

// CuNNy is LGPL-3.0-or-later; keep THIRD_PARTY_NOTICES.txt in sync.



struct CuNNyParams {
    source_width: u32,
    source_height: u32,
    output_width: u32,
    output_height: u32,
};

@group(0) @binding(0) var source_tex: texture_2d<f32>;
@group(0) @binding(1) var input0_tex: texture_2d<f32>;
@group(0) @binding(2) var input1_tex: texture_2d<f32>;
@group(0) @binding(3) var input2_tex: texture_2d<f32>;
@group(0) @binding(4) var input3_tex: texture_2d<f32>;
@group(0) @binding(5) var input4_tex: texture_2d<f32>;
@group(0) @binding(6) var input5_tex: texture_2d<f32>;
@group(0) @binding(7) var input6_tex: texture_2d<f32>;
@group(0) @binding(8) var input7_tex: texture_2d<f32>;
@group(0) @binding(9) var out0_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(10) var out1_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(11) var out2_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(12) var final_tex: texture_storage_2d<rgba8unorm, write>;
@group(0) @binding(13) var<uniform> params: CuNNyParams;

fn clamp_source_coord(coord: vec2<i32>) -> vec2<i32> {
    return clamp(coord, vec2<i32>(0, 0), vec2<i32>(i32(params.source_width) - 1, i32(params.source_height) - 1));
}

fn load_source_luma(coord: vec2<i32>, dx: i32, dy: i32) -> f32 {
    let c = textureLoad(source_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0).rgb;
    return dot(c, vec3<f32>(0.299, 0.587, 0.114));
}
fn load_input0(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input0_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input1(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input1_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input2(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input2_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input3(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input3_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input4(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input4_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input5(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input5_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input6(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input6_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }
fn load_input7(coord: vec2<i32>, dx: i32, dy: i32) -> vec4<f32> { return textureLoad(input7_tex, clamp_source_coord(coord + vec2<i32>(dx, dy)), 0); }

fn sample_source_rgb_for_output(out_coord: vec2<i32>) -> vec3<f32> {
    let source_scale = vec2<f32>(f32(params.source_width) / f32(params.output_width), f32(params.source_height) / f32(params.output_height));
    let source_pos = (vec2<f32>(out_coord) + vec2<f32>(0.5)) * source_scale - vec2<f32>(0.5);
    let p0f = floor(source_pos);
    let t = source_pos - p0f;
    let p0_base = vec2<i32>(i32(p0f.x), i32(p0f.y));
    let p0 = clamp_source_coord(p0_base);
    let p1 = clamp_source_coord(p0_base + vec2<i32>(1, 1));
    let c00 = textureLoad(source_tex, p0, 0).rgb;
    let c10 = textureLoad(source_tex, vec2<i32>(p1.x, p0.y), 0).rgb;
    let c01 = textureLoad(source_tex, vec2<i32>(p0.x, p1.y), 0).rgb;
    let c11 = textureLoad(source_tex, p1, 0).rgb;
    return mix(mix(c00, c10, t.x), mix(c01, c11, t.x), t.y);
}
fn sample_source_luma_for_output(out_coord: vec2<i32>) -> f32 {
    return dot(sample_source_rgb_for_output(out_coord), vec3<f32>(0.299, 0.587, 0.114));
}
fn rgb_to_yuv(rgb: vec3<f32>) -> vec3<f32> { return vec3<f32>(dot(rgb, vec3<f32>(0.299, 0.587, 0.114)), dot(rgb, vec3<f32>(-0.169, -0.331, 0.5)), dot(rgb, vec3<f32>(0.5, -0.419, -0.081))); }
fn yuv_to_rgb(yuv: vec3<f32>) -> vec3<f32> { return vec3<f32>(dot(yuv, vec3<f32>(1.0, -0.00093, 1.401687)), dot(yuv, vec3<f32>(1.0, -0.3437, -0.71417)), dot(yuv, vec3<f32>(1.0, 1.77216, 0.00099))); }
fn write_output_luma_value(out_coord: vec2<i32>, luma: f32) {
    if (out_coord.x >= i32(params.output_width) || out_coord.y >= i32(params.output_height)) { return; }
    let rgb = sample_source_rgb_for_output(out_coord);
    var yuv = rgb_to_yuv(rgb);
    yuv.x = clamp(luma, 0.0, 1.0);
    textureStore(final_tex, out_coord, vec4<f32>(clamp(yuv_to_rgb(yuv), vec3<f32>(0.0), vec3<f32>(1.0)), 1.0));
}



// CuNNy-veryfast-SOFT-in
@compute @workgroup_size(8, 8)
fn cunny_veryfast_soft_pass_0(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    var r1 = vec4<f32>(0.0);
    var s0_0_0 = load_source_luma(coord, -1, -1);
    var s0_0_1 = load_source_luma(coord, 0, -1);
    var s0_0_2 = load_source_luma(coord, 1, -1);
    var s0_1_0 = load_source_luma(coord, -1, 0);
    var s0_1_1 = load_source_luma(coord, 0, 0);
    var s0_1_2 = load_source_luma(coord, 1, 0);
    var s0_2_0 = load_source_luma(coord, -1, 1);
    var s0_2_1 = load_source_luma(coord, 0, 1);
    var s0_2_2 = load_source_luma(coord, 1, 1);
    r0 += vec4<f32>(-4.261e-02, -3.667e-02, -1.154e-02, -1.987e-01) * s0_0_0;
    r1 += vec4<f32>(1.432e-02, -1.051e-02, 2.980e-03, 6.233e-02) * s0_0_0;
    r0 += vec4<f32>(1.150e+00, 3.870e-02, -1.912e-02, -1.018e-01) * s0_0_1;
    r1 += vec4<f32>(2.738e-02, 7.880e-02, -2.794e-02, 2.159e-01) * s0_0_1;
    r0 += vec4<f32>(1.466e-02, 1.814e-02, 3.406e-02, 3.213e-01) * s0_0_2;
    r1 += vec4<f32>(-4.349e-02, -5.303e-02, 2.717e-02, -8.656e-02) * s0_0_2;
    r0 += vec4<f32>(-6.192e-03, 3.412e-01, 1.076e+00, 8.554e-01) * s0_1_0;
    r1 += vec4<f32>(-3.558e-02, 5.132e-02, -1.138e-02, 3.005e-01) * s0_1_0;
    r0 += vec4<f32>(-1.105e+00, 2.220e-01, -9.474e-01, -9.155e-01) * s0_1_1;
    r1 += vec4<f32>(-1.059e+00, -1.333e-01, -1.073e+00, -1.152e+00) * s0_1_1;
    r0 += vec4<f32>(-1.126e-02, 1.069e-02, -1.051e-01, 7.108e-03) * s0_1_2;
    r1 += vec4<f32>(1.090e+00, 2.574e-01, -2.334e-02, 2.402e-01) * s0_1_2;
    r0 += vec4<f32>(4.406e-02, 8.321e-02, -4.105e-02, 2.105e-01) * s0_2_0;
    r1 += vec4<f32>(1.507e-02, -1.744e-02, 3.503e-05, -1.016e-01) * s0_2_0;
    r0 += vec4<f32>(-4.078e-02, -7.062e-01, -6.218e-02, 4.684e-02) * s0_2_1;
    r1 += vec4<f32>(-1.002e-02, -1.030e-01, 1.098e+00, 2.858e-01) * s0_2_1;
    r0 += vec4<f32>(-5.676e-03, 1.173e-02, 7.469e-02, -2.327e-01) * s0_2_2;
    r1 += vec4<f32>(-5.805e-03, -4.049e-02, 4.043e-03, 4.426e-02) * s0_2_2;
    r0 += vec4<f32>(-1.137e-03, -3.262e-04, -2.050e-03, -2.276e-03);
    r0 = clamp(r0, vec4<f32>(0.0), vec4<f32>(1.0));
    textureStore(out0_tex, coord, r0);
    r1 += vec4<f32>(-5.205e-04, 1.480e-02, 2.195e-05, -1.857e-03);
    r1 = clamp(r1, vec4<f32>(0.0), vec4<f32>(1.0));
    textureStore(out1_tex, coord, r1);
}

// CuNNy-veryfast-SOFT-conv1
@compute @workgroup_size(8, 8)
fn cunny_veryfast_soft_pass_1(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    var r1 = vec4<f32>(0.0);
    var s0_0_0 = load_input0(coord, -1, -1);
    var s0_0_1 = load_input0(coord, 0, -1);
    var s0_0_2 = load_input0(coord, 1, -1);
    var s0_1_0 = load_input0(coord, -1, 0);
    var s0_1_1 = load_input0(coord, 0, 0);
    var s0_1_2 = load_input0(coord, 1, 0);
    var s0_2_0 = load_input0(coord, -1, 1);
    var s0_2_1 = load_input0(coord, 0, 1);
    var s0_2_2 = load_input0(coord, 1, 1);
    var s1_0_0 = load_input1(coord, -1, -1);
    var s1_0_1 = load_input1(coord, 0, -1);
    var s1_0_2 = load_input1(coord, 1, -1);
    var s1_1_0 = load_input1(coord, -1, 0);
    var s1_1_1 = load_input1(coord, 0, 0);
    var s1_1_2 = load_input1(coord, 1, 0);
    var s1_2_0 = load_input1(coord, -1, 1);
    var s1_2_1 = load_input1(coord, 0, 1);
    var s1_2_2 = load_input1(coord, 1, 1);
    r0 += vec4<f32>(dot(s0_0_0, vec4<f32>(-2.317e-02, 2.302e-01, -8.387e-03, -5.112e-02)), dot(s0_0_0, vec4<f32>(5.272e-02, -3.604e-01, 1.322e-01, -2.141e-02)), dot(s0_0_0, vec4<f32>(-3.439e-02, 3.614e-02, 1.868e-02, -5.701e-02)), dot(s0_0_0, vec4<f32>(-1.015e-01, 1.551e-01, -1.441e-01, 6.522e-02)));
    r1 += vec4<f32>(dot(s0_0_0, vec4<f32>(9.446e-03, 3.270e-01, -2.290e-01, 2.060e-01)), dot(s0_0_0, vec4<f32>(-1.047e-02, 3.117e-03, 3.265e-03, -5.508e-02)), dot(s0_0_0, vec4<f32>(2.699e-02, 4.701e-02, -5.005e-03, 2.585e-02)), dot(s0_0_0, vec4<f32>(1.361e-01, 1.144e-01, -7.935e-02, 1.577e-01)));
    r0 += vec4<f32>(dot(s0_0_1, vec4<f32>(1.013e-01, 1.000e+00, -2.582e-01, 1.291e-01)), dot(s0_0_1, vec4<f32>(-7.155e-02, -6.657e-02, -1.388e-01, 1.801e-01)), dot(s0_0_1, vec4<f32>(8.903e-03, 6.601e-03, 2.061e-01, -3.144e-01)), dot(s0_0_1, vec4<f32>(9.070e-03, -3.300e-01, 5.890e-02, -2.903e-02)));
    r1 += vec4<f32>(dot(s0_0_1, vec4<f32>(6.140e-02, -1.210e-01, 2.073e-01, 2.313e-01)), dot(s0_0_1, vec4<f32>(-2.030e-03, -1.077e-01, 5.413e-02, 8.847e-03)), dot(s0_0_1, vec4<f32>(3.199e-02, -1.639e-01, -1.252e-01, 1.771e-01)), dot(s0_0_1, vec4<f32>(-7.252e-02, -3.029e-01, -4.111e-01, -1.342e-01)));
    r0 += vec4<f32>(dot(s0_0_2, vec4<f32>(-3.009e-02, 4.093e-01, 9.091e-03, -1.712e-01)), dot(s0_0_2, vec4<f32>(-6.471e-02, -2.255e-01, -1.937e-01, 1.555e-01)), dot(s0_0_2, vec4<f32>(9.174e-02, 7.047e-02, 1.631e-01, -2.085e-01)), dot(s0_0_2, vec4<f32>(-3.098e-02, 2.416e-02, 6.546e-03, -4.236e-02)));
    r1 += vec4<f32>(dot(s0_0_2, vec4<f32>(-7.917e-02, -1.622e-01, 3.848e-02, 1.613e-01)), dot(s0_0_2, vec4<f32>(-1.012e-02, 1.324e-01, -6.404e-02, 1.367e-02)), dot(s0_0_2, vec4<f32>(1.778e-02, 2.686e-01, -3.179e-02, -4.429e-03)), dot(s0_0_2, vec4<f32>(-6.940e-02, -2.105e-01, -6.604e-02, 1.431e-01)));
    r0 += vec4<f32>(dot(s0_1_0, vec4<f32>(-7.480e-01, -1.374e-01, -5.237e-02, 6.013e-04)), dot(s0_1_0, vec4<f32>(1.948e-01, -1.338e-01, 8.106e-02, 1.929e-01)), dot(s0_1_0, vec4<f32>(-8.205e-02, -1.935e-01, 1.817e-01, -1.929e-01)), dot(s0_1_0, vec4<f32>(-1.245e-01, 2.278e-02, -1.952e-01, 6.607e-02)));
    r1 += vec4<f32>(dot(s0_1_0, vec4<f32>(-2.201e-01, 1.890e-02, -5.123e-01, 4.733e-01)), dot(s0_1_0, vec4<f32>(-4.525e-02, 5.608e-02, -1.687e-02, 2.169e-02)), dot(s0_1_0, vec4<f32>(1.480e-01, 6.244e-02, -1.088e-02, -6.417e-02)), dot(s0_1_0, vec4<f32>(3.586e-01, 1.859e-01, -4.600e-01, 4.324e-01)));
    r0 += vec4<f32>(dot(s0_1_1, vec4<f32>(-1.000e+00, 5.582e-01, -7.529e-01, -3.195e-01)), dot(s0_1_1, vec4<f32>(1.159e-01, -4.866e-01, -4.160e-01, 6.345e-01)), dot(s0_1_1, vec4<f32>(7.523e-02, -2.840e-02, 2.048e-01, -1.552e-01)), dot(s0_1_1, vec4<f32>(1.068e-01, 3.717e-02, 7.513e-01, -1.220e-01)));
    r1 += vec4<f32>(dot(s0_1_1, vec4<f32>(7.022e-03, -4.821e-01, -2.472e-01, 4.405e-01)), dot(s0_1_1, vec4<f32>(6.587e-02, 6.930e-03, 2.856e-01, 1.999e-01)), dot(s0_1_1, vec4<f32>(3.896e-01, 5.641e-03, 1.287e-01, -5.410e-02)), dot(s0_1_1, vec4<f32>(3.266e-01, -1.459e-01, 1.043e-01, 3.628e-01)));
    r0 += vec4<f32>(dot(s0_1_2, vec4<f32>(-8.321e-02, -3.715e-01, 2.579e-01, -2.288e-01)), dot(s0_1_2, vec4<f32>(-2.656e-01, -3.898e-01, -2.481e-01, -1.697e-01)), dot(s0_1_2, vec4<f32>(9.260e-02, 1.939e-01, 3.015e-01, 1.585e-01)), dot(s0_1_2, vec4<f32>(5.405e-02, -2.749e-02, 3.142e-01, -1.532e-01)));
    r1 += vec4<f32>(dot(s0_1_2, vec4<f32>(1.289e-01, 4.812e-01, 5.598e-02, 4.388e-01)), dot(s0_1_2, vec4<f32>(-5.706e-02, 3.518e-02, -5.093e-02, 7.300e-03)), dot(s0_1_2, vec4<f32>(1.033e-01, -1.272e-01, 1.023e-02, -7.831e-02)), dot(s0_1_2, vec4<f32>(2.068e-01, 4.975e-02, -1.706e-01, 4.584e-01)));
    r0 += vec4<f32>(dot(s0_2_0, vec4<f32>(-7.988e-02, -9.423e-02, 2.810e-01, -2.454e-01)), dot(s0_2_0, vec4<f32>(6.628e-01, -5.755e-02, -2.791e-01, 3.903e-01)), dot(s0_2_0, vec4<f32>(9.325e-02, -1.017e-01, 2.305e-01, -9.890e-02)), dot(s0_2_0, vec4<f32>(4.713e-02, 4.653e-02, 5.082e-02, -1.060e-01)));
    r1 += vec4<f32>(dot(s0_2_0, vec4<f32>(-3.171e-01, -1.256e-01, -6.054e-02, -5.528e-02)), dot(s0_2_0, vec4<f32>(2.223e-01, -2.312e-02, 2.838e-02, 5.076e-03)), dot(s0_2_0, vec4<f32>(1.016e-01, -1.605e-02, 4.108e-02, -5.979e-02)), dot(s0_2_0, vec4<f32>(-2.997e-01, -1.470e-01, -1.450e-01, 7.576e-02)));
    r0 += vec4<f32>(dot(s0_2_1, vec4<f32>(4.734e-01, 1.057e-01, 2.541e-01, -3.576e-01)), dot(s0_2_1, vec4<f32>(-7.768e-01, -1.828e-02, -7.897e-02, 1.715e-01)), dot(s0_2_1, vec4<f32>(-4.875e-01, 1.382e-01, 2.929e-02, -2.688e-02)), dot(s0_2_1, vec4<f32>(1.294e-01, -9.510e-02, 2.042e-01, 8.829e-03)));
    r1 += vec4<f32>(dot(s0_2_1, vec4<f32>(-1.000e+00, -4.371e-02, -4.072e-01, 1.880e-01)), dot(s0_2_1, vec4<f32>(-4.001e-01, -1.540e-02, 4.472e-02, 3.842e-02)), dot(s0_2_1, vec4<f32>(-5.633e-02, 7.458e-02, 1.508e-01, 2.732e-03)), dot(s0_2_1, vec4<f32>(-5.902e-01, 3.601e-03, -3.623e-01, 1.093e-01)));
    r0 += vec4<f32>(dot(s0_2_2, vec4<f32>(8.522e-02, 1.843e-01, 2.998e-01, 1.074e-01)), dot(s0_2_2, vec4<f32>(4.538e-02, 4.129e-02, 2.466e-01, -5.736e-02)), dot(s0_2_2, vec4<f32>(-2.472e-02, -1.873e-01, -1.492e-01, -6.774e-02)), dot(s0_2_2, vec4<f32>(-5.333e-02, 8.822e-02, 6.354e-02, 1.315e-02)));
    r1 += vec4<f32>(dot(s0_2_2, vec4<f32>(-3.185e-02, 3.185e-02, -2.378e-01, -2.593e-02)), dot(s0_2_2, vec4<f32>(-5.508e-03, 2.248e-02, -5.526e-02, 2.126e-02)), dot(s0_2_2, vec4<f32>(-7.594e-02, -6.870e-03, 1.330e-02, 2.943e-02)), dot(s0_2_2, vec4<f32>(1.717e-02, -9.904e-02, -1.314e-01, 7.594e-03)));
    r0 += vec4<f32>(dot(s1_0_0, vec4<f32>(-1.681e-02, 4.185e-01, -4.593e-02, 2.548e-02)), dot(s1_0_0, vec4<f32>(3.207e-02, -3.211e-01, -1.340e-02, -2.094e-02)), dot(s1_0_0, vec4<f32>(1.561e-02, -1.347e-01, 3.529e-02, 3.183e-02)), dot(s1_0_0, vec4<f32>(-3.717e-03, 3.626e-01, -1.208e-01, 1.154e-01)));
    r1 += vec4<f32>(dot(s1_0_0, vec4<f32>(-1.737e-01, 1.948e-01, -6.924e-02, 5.236e-02)), dot(s1_0_0, vec4<f32>(-4.892e-02, 1.117e-01, 1.006e-02, -4.419e-03)), dot(s1_0_0, vec4<f32>(1.412e-02, 1.811e-01, -2.183e-02, -7.115e-02)), dot(s1_0_0, vec4<f32>(8.224e-02, -2.939e-01, -5.577e-02, -1.303e-01)));
    r0 += vec4<f32>(dot(s1_0_1, vec4<f32>(1.610e-01, -1.103e-01, -5.413e-01, -2.798e-01)), dot(s1_0_1, vec4<f32>(-2.277e-02, -7.833e-02, -1.830e-01, 1.855e-01)), dot(s1_0_1, vec4<f32>(-1.859e-01, 2.868e-01, 1.193e-01, 5.787e-02)), dot(s1_0_1, vec4<f32>(-2.116e-02, -1.191e-01, -2.046e-01, 2.597e-02)));
    r1 += vec4<f32>(dot(s1_0_1, vec4<f32>(1.322e-01, -2.212e-01, 4.108e-01, -4.759e-01)), dot(s1_0_1, vec4<f32>(1.811e-02, -1.489e-01, 5.211e-02, -7.631e-02)), dot(s1_0_1, vec4<f32>(2.864e-01, -2.653e-01, -4.170e-01, 4.210e-02)), dot(s1_0_1, vec4<f32>(-1.179e-01, -7.070e-02, 2.821e-01, 5.473e-02)));
    r0 += vec4<f32>(dot(s1_0_2, vec4<f32>(1.004e-01, -1.213e-01, 2.535e-01, -1.846e-01)), dot(s1_0_2, vec4<f32>(7.086e-03, 1.241e-01, -5.180e-02, 9.316e-03)), dot(s1_0_2, vec4<f32>(-2.172e-02, -1.095e-01, 8.519e-02, 1.699e-02)), dot(s1_0_2, vec4<f32>(4.274e-02, -3.957e-02, -1.098e-01, 9.931e-02)));
    r1 += vec4<f32>(dot(s1_0_2, vec4<f32>(-1.504e-01, -3.133e-01, 3.561e-02, 2.098e-01)), dot(s1_0_2, vec4<f32>(-6.006e-02, 1.294e-02, -4.294e-02, 1.454e-01)), dot(s1_0_2, vec4<f32>(3.918e-02, -2.019e-02, 2.705e-01, 1.316e-01)), dot(s1_0_2, vec4<f32>(-1.155e-01, -6.971e-02, -9.707e-02, 2.570e-01)));
    r0 += vec4<f32>(dot(s1_1_0, vec4<f32>(-1.000e+00, 5.836e-01, -8.173e-02, 2.366e-01)), dot(s1_1_0, vec4<f32>(1.694e-01, 6.854e-03, -7.347e-02, -2.064e-02)), dot(s1_1_0, vec4<f32>(4.577e-01, 2.045e-02, 1.171e-01, -2.124e-01)), dot(s1_1_0, vec4<f32>(-3.535e-01, 6.627e-03, -1.382e-01, 3.978e-01)));
    r1 += vec4<f32>(dot(s1_1_0, vec4<f32>(-1.000e+00, -3.841e-01, -9.782e-02, 4.195e-01)), dot(s1_1_0, vec4<f32>(3.090e-02, -1.475e-01, -1.138e-02, 6.958e-02)), dot(s1_1_0, vec4<f32>(-3.174e-01, -1.543e-01, 2.073e-02, -3.451e-02)), dot(s1_1_0, vec4<f32>(-7.609e-01, -3.232e-01, -2.145e-01, 3.274e-01)));
    r0 += vec4<f32>(dot(s1_1_1, vec4<f32>(-4.615e-01, -1.987e-01, -9.387e-01, 3.647e-01)), dot(s1_1_1, vec4<f32>(-2.588e-01, -6.211e-01, 4.447e-01, 1.860e-01)), dot(s1_1_1, vec4<f32>(1.933e-01, -4.863e-01, 2.171e-01, -1.683e-01)), dot(s1_1_1, vec4<f32>(1.677e-01, -3.242e-01, 4.502e-01, -2.009e-01)));
    r1 += vec4<f32>(dot(s1_1_1, vec4<f32>(2.377e-01, 4.559e-01, 4.924e-02, -2.962e-02)), dot(s1_1_1, vec4<f32>(1.304e-01, 4.012e-02, 7.569e-01, -2.235e-01)), dot(s1_1_1, vec4<f32>(3.446e-01, 5.323e-01, 5.300e-03, -3.263e-01)), dot(s1_1_1, vec4<f32>(1.349e-01, -1.730e-01, 8.070e-02, -2.233e-01)));
    r0 += vec4<f32>(dot(s1_1_2, vec4<f32>(2.471e-02, -4.435e-02, 2.428e-01, -1.479e-01)), dot(s1_1_2, vec4<f32>(-2.320e-01, 4.219e-01, -1.633e-02, 5.801e-01)), dot(s1_1_2, vec4<f32>(7.255e-02, -9.931e-02, -2.124e-01, -6.412e-02)), dot(s1_1_2, vec4<f32>(-4.576e-02, 1.938e-01, -1.719e-02, -5.783e-02)));
    r1 += vec4<f32>(dot(s1_1_2, vec4<f32>(4.273e-02, -1.894e-01, -4.747e-01, 1.916e-01)), dot(s1_1_2, vec4<f32>(-2.143e-02, -5.881e-02, 2.684e-03, -1.311e-02)), dot(s1_1_2, vec4<f32>(1.765e-02, -1.324e-01, 1.724e-01, -7.760e-02)), dot(s1_1_2, vec4<f32>(4.531e-02, -5.145e-02, 4.132e-02, -1.156e-01)));
    r0 += vec4<f32>(dot(s1_2_0, vec4<f32>(4.724e-01, -9.036e-02, 1.693e-01, -2.840e-01)), dot(s1_2_0, vec4<f32>(1.370e-01, 6.226e-02, -4.528e-02, -1.684e-01)), dot(s1_2_0, vec4<f32>(2.607e-01, -1.531e-01, -8.536e-02, -1.363e-01)), dot(s1_2_0, vec4<f32>(-2.919e-03, -1.695e-01, 9.589e-03, 4.022e-02)));
    r1 += vec4<f32>(dot(s1_2_0, vec4<f32>(-2.407e-01, 7.444e-01, 4.696e-02, 2.490e-01)), dot(s1_2_0, vec4<f32>(1.032e-01, 4.426e-02, -2.167e-02, -5.826e-02)), dot(s1_2_0, vec4<f32>(-5.434e-02, -9.009e-02, -2.013e-02, -5.901e-03)), dot(s1_2_0, vec4<f32>(-1.949e-01, 6.895e-01, 1.606e-02, 6.904e-02)));
    r0 += vec4<f32>(dot(s1_2_1, vec4<f32>(8.377e-02, -5.925e-01, 2.524e-02, -3.398e-01)), dot(s1_2_1, vec4<f32>(-3.638e-01, 2.580e-01, -2.618e-02, -2.901e-01)), dot(s1_2_1, vec4<f32>(-9.553e-01, -1.840e-01, -6.612e-01, -1.492e-01)), dot(s1_2_1, vec4<f32>(-2.787e-02, 5.586e-02, 3.338e-02, -1.301e-01)));
    r1 += vec4<f32>(dot(s1_2_1, vec4<f32>(2.156e-01, -1.616e-01, -1.525e-01, 4.132e-01)), dot(s1_2_1, vec4<f32>(-9.540e-02, -4.252e-02, -6.038e-02, 6.341e-02)), dot(s1_2_1, vec4<f32>(1.815e-01, 1.093e-02, 3.698e-02, -6.102e-02)), dot(s1_2_1, vec4<f32>(-8.468e-02, 2.916e-01, -9.251e-02, 4.000e-01)));
    r0 += vec4<f32>(dot(s1_2_2, vec4<f32>(-1.914e-02, 1.745e-02, -2.011e-02, 1.182e-01)), dot(s1_2_2, vec4<f32>(5.435e-02, 2.084e-01, 1.116e-01, -1.768e-01)), dot(s1_2_2, vec4<f32>(-1.700e-01, 5.780e-01, -2.123e-01, 1.549e-01)), dot(s1_2_2, vec4<f32>(-1.910e-02, -1.332e-02, -5.005e-02, 9.116e-02)));
    r1 += vec4<f32>(dot(s1_2_2, vec4<f32>(1.022e-01, -1.104e-01, 7.377e-03, -8.377e-02)), dot(s1_2_2, vec4<f32>(-1.014e-02, 1.753e-01, 3.992e-03, -3.220e-04)), dot(s1_2_2, vec4<f32>(-4.234e-02, -6.934e-02, -7.477e-03, 1.057e-01)), dot(s1_2_2, vec4<f32>(8.255e-02, -8.916e-02, -2.571e-02, -2.563e-02)));
    r0 = clamp(r0, vec4<f32>(0.0), vec4<f32>(1.0));
    textureStore(out0_tex, coord, r0);
    r1 = clamp(r1, vec4<f32>(0.0), vec4<f32>(1.0));
    textureStore(out1_tex, coord, r1);
}

// CuNNy-veryfast-SOFT-conv2
@compute @workgroup_size(8, 8)
fn cunny_veryfast_soft_pass_2(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    var r0 = vec4<f32>(0.0);
    var s0_0_0 = load_input0(coord, -1, -1);
    var s0_0_1 = load_input0(coord, 0, -1);
    var s0_0_2 = load_input0(coord, 1, -1);
    var s0_1_0 = load_input0(coord, -1, 0);
    var s0_1_1 = load_input0(coord, 0, 0);
    var s0_1_2 = load_input0(coord, 1, 0);
    var s0_2_0 = load_input0(coord, -1, 1);
    var s0_2_1 = load_input0(coord, 0, 1);
    var s0_2_2 = load_input0(coord, 1, 1);
    var s1_0_0 = load_input1(coord, -1, -1);
    var s1_0_1 = load_input1(coord, 0, -1);
    var s1_0_2 = load_input1(coord, 1, -1);
    var s1_1_0 = load_input1(coord, -1, 0);
    var s1_1_1 = load_input1(coord, 0, 0);
    var s1_1_2 = load_input1(coord, 1, 0);
    var s1_2_0 = load_input1(coord, -1, 1);
    var s1_2_1 = load_input1(coord, 0, 1);
    var s1_2_2 = load_input1(coord, 1, 1);
    r0 += vec4<f32>(dot(s0_0_0, vec4<f32>(2.165e-02, -8.661e-02, -1.757e-02, -3.657e-02)), dot(s0_0_0, vec4<f32>(3.026e-02, -4.209e-02, 3.272e-02, -3.421e-02)), dot(s0_0_0, vec4<f32>(4.051e-02, -9.197e-02, 2.691e-02, 9.457e-02)), dot(s0_0_0, vec4<f32>(3.915e-02, -8.715e-02, 3.720e-02, -9.498e-02)));
    r0 += vec4<f32>(dot(s0_0_1, vec4<f32>(-3.844e-03, 1.378e-01, -3.336e-02, 1.859e-01)), dot(s0_0_1, vec4<f32>(1.111e-01, -1.463e-02, 6.568e-03, -1.530e-01)), dot(s0_0_1, vec4<f32>(-2.155e-01, -2.997e-01, -1.558e-01, 2.372e-01)), dot(s0_0_1, vec4<f32>(8.561e-02, -1.721e-01, -1.757e-01, -5.114e-02)));
    r0 += vec4<f32>(dot(s0_0_2, vec4<f32>(-1.593e-01, -1.508e-01, -5.230e-02, -2.542e-02)), dot(s0_0_2, vec4<f32>(1.325e-02, -1.444e-02, 7.373e-03, -5.521e-02)), dot(s0_0_2, vec4<f32>(-9.455e-02, 5.664e-02, 9.302e-02, 8.569e-02)), dot(s0_0_2, vec4<f32>(2.536e-02, 6.149e-02, 1.058e-01, -8.126e-02)));
    r0 += vec4<f32>(dot(s0_1_0, vec4<f32>(7.059e-03, -4.626e-02, 5.796e-02, -5.518e-02)), dot(s0_1_0, vec4<f32>(-2.256e-01, -6.717e-03, -3.883e-01, 1.636e-01)), dot(s0_1_0, vec4<f32>(-3.135e-01, -2.683e-02, -2.855e-02, 1.162e-01)), dot(s0_1_0, vec4<f32>(-6.569e-02, 3.845e-02, -7.155e-02, 4.832e-02)));
    r0 += vec4<f32>(dot(s0_1_1, vec4<f32>(-3.423e-01, -3.835e-01, -1.139e-01, 1.564e-01)), dot(s0_1_1, vec4<f32>(-3.567e-01, -3.271e-01, -6.856e-02, 1.209e-02)), dot(s0_1_1, vec4<f32>(1.446e-02, -1.225e-01, -3.757e-02, -2.389e-01)), dot(s0_1_1, vec4<f32>(-4.825e-01, -3.975e-01, -3.596e-01, 9.043e-02)));
    r0 += vec4<f32>(dot(s0_1_2, vec4<f32>(-7.499e-02, -1.620e-02, 1.056e-01, -1.373e-01)), dot(s0_1_2, vec4<f32>(-1.461e-01, 1.028e-01, 9.988e-02, 2.056e-02)), dot(s0_1_2, vec4<f32>(-1.823e-02, 6.275e-03, 2.519e-02, -1.912e-02)), dot(s0_1_2, vec4<f32>(-2.821e-01, 7.592e-02, 1.703e-01, 1.412e-02)));
    r0 += vec4<f32>(dot(s0_2_0, vec4<f32>(-1.091e-02, -4.826e-02, -1.070e-02, -6.667e-02)), dot(s0_2_0, vec4<f32>(-1.138e-01, -1.227e-01, 1.071e-01, -2.303e-01)), dot(s0_2_0, vec4<f32>(-3.009e-02, 2.871e-02, 3.567e-02, 3.178e-02)), dot(s0_2_0, vec4<f32>(-1.811e-01, -5.174e-02, 4.503e-02, -8.346e-02)));
    r0 += vec4<f32>(dot(s0_2_1, vec4<f32>(-1.034e-01, -1.026e-01, 4.561e-02, 3.133e-01)), dot(s0_2_1, vec4<f32>(-4.693e-02, -7.886e-02, 2.164e-02, 4.816e-02)), dot(s0_2_1, vec4<f32>(-3.141e-04, 4.021e-03, -3.332e-02, 8.110e-04)), dot(s0_2_1, vec4<f32>(-5.685e-02, -8.618e-02, 1.561e-02, 1.741e-01)));
    r0 += vec4<f32>(dot(s0_2_2, vec4<f32>(-7.156e-02, -3.332e-02, 5.886e-02, 6.617e-02)), dot(s0_2_2, vec4<f32>(-3.047e-02, -1.972e-02, 7.158e-02, 4.597e-02)), dot(s0_2_2, vec4<f32>(-1.382e-02, 3.408e-05, -6.510e-03, 1.283e-02)), dot(s0_2_2, vec4<f32>(-6.068e-02, -5.339e-02, 6.955e-02, 2.872e-02)));
    r0 += vec4<f32>(dot(s1_0_0, vec4<f32>(3.012e-02, 1.995e-02, 3.895e-03, 1.514e-02)), dot(s1_0_0, vec4<f32>(-2.653e-02, -2.607e-02, 1.388e-02, -4.564e-02)), dot(s1_0_0, vec4<f32>(1.491e-02, 2.725e-01, 1.098e-02, -7.828e-02)), dot(s1_0_0, vec4<f32>(2.057e-02, 5.896e-02, 1.906e-02, -1.521e-02)));
    r0 += vec4<f32>(dot(s1_0_1, vec4<f32>(-5.846e-03, -1.377e-01, 2.435e-02, -3.703e-02)), dot(s1_0_1, vec4<f32>(-5.346e-03, -8.246e-02, -2.421e-02, 1.571e-02)), dot(s1_0_1, vec4<f32>(-1.548e-01, 1.596e-01, -6.735e-02, -7.368e-02)), dot(s1_0_1, vec4<f32>(-2.817e-02, -1.051e-01, -5.897e-02, 3.135e-02)));
    r0 += vec4<f32>(dot(s1_0_2, vec4<f32>(-9.886e-03, 1.056e-01, -4.285e-02, 1.097e-03)), dot(s1_0_2, vec4<f32>(-5.964e-03, 3.212e-02, -5.957e-03, -2.363e-02)), dot(s1_0_2, vec4<f32>(-1.232e-03, -2.059e-01, -2.441e-02, 7.662e-03)), dot(s1_0_2, vec4<f32>(-2.480e-02, -2.742e-02, -2.021e-02, -1.922e-02)));
    r0 += vec4<f32>(dot(s1_1_0, vec4<f32>(2.475e-02, 9.528e-02, -1.004e-01, 1.271e-02)), dot(s1_1_0, vec4<f32>(1.587e-01, 6.513e-02, 3.769e-01, -2.648e-01)), dot(s1_1_0, vec4<f32>(4.623e-02, -1.196e-01, 2.771e-01, -4.736e-02)), dot(s1_1_0, vec4<f32>(2.221e-01, -1.614e-02, 2.510e-01, -8.565e-02)));
    r0 += vec4<f32>(dot(s1_1_1, vec4<f32>(-4.147e-02, 7.715e-01, -2.961e-02, 7.615e-02)), dot(s1_1_1, vec4<f32>(-9.884e-02, 4.817e-01, -5.356e-02, -2.710e-01)), dot(s1_1_1, vec4<f32>(-4.189e-01, 3.018e-01, 3.162e-01, 3.433e-01)), dot(s1_1_1, vec4<f32>(-3.886e-01, 8.706e-01, 7.178e-02, -3.467e-01)));
    r0 += vec4<f32>(dot(s1_1_2, vec4<f32>(-5.225e-02, 1.853e-01, 5.732e-02, -6.596e-02)), dot(s1_1_2, vec4<f32>(-1.094e-03, -1.053e-01, -5.526e-03, -3.064e-02)), dot(s1_1_2, vec4<f32>(-4.061e-02, -9.647e-02, 3.870e-02, -2.771e-02)), dot(s1_1_2, vec4<f32>(2.662e-02, -1.398e-01, 1.720e-02, -7.296e-02)));
    r0 += vec4<f32>(dot(s1_2_0, vec4<f32>(4.133e-02, 7.545e-02, 6.839e-02, 9.340e-03)), dot(s1_2_0, vec4<f32>(9.448e-03, 8.521e-02, 1.392e-01, 1.538e-02)), dot(s1_2_0, vec4<f32>(-1.685e-02, -7.719e-02, -7.152e-02, -3.676e-02)), dot(s1_2_0, vec4<f32>(1.614e-02, 2.543e-02, 7.443e-02, -4.460e-02)));
    r0 += vec4<f32>(dot(s1_2_1, vec4<f32>(-9.161e-02, -3.661e-02, -3.546e-02, 1.245e-01)), dot(s1_2_1, vec4<f32>(-3.467e-01, 1.258e-01, 2.008e-01, 3.584e-01)), dot(s1_2_1, vec4<f32>(5.091e-02, 4.126e-04, 5.913e-03, -5.790e-02)), dot(s1_2_1, vec4<f32>(-2.385e-01, 6.453e-02, 1.685e-01, 3.434e-01)));
    r0 += vec4<f32>(dot(s1_2_2, vec4<f32>(-3.213e-02, -3.755e-02, 4.865e-03, -7.209e-03)), dot(s1_2_2, vec4<f32>(-2.484e-02, -8.872e-02, 9.485e-03, -5.040e-02)), dot(s1_2_2, vec4<f32>(-7.514e-03, 4.703e-03, 6.023e-03, -7.514e-03)), dot(s1_2_2, vec4<f32>(-4.339e-02, -8.078e-02, 1.481e-02, 5.677e-02)));
    r0 = clamp(r0, vec4<f32>(0.0), vec4<f32>(1.0));
    textureStore(out0_tex, coord, r0);
}

// CuNNy-veryfast-SOFT-out-shuffle
@compute @workgroup_size(8, 8)
fn cunny_veryfast_soft_pass_3(@builtin(global_invocation_id) global_id: vec3<u32>) {
    if (global_id.x >= params.source_width || global_id.y >= params.source_height) { return; }
    let coord = vec2<i32>(i32(global_id.x), i32(global_id.y));
    let base = coord * vec2<i32>(2, 2);
    var r0 = vec4<f32>(0.0);
    var s0_0_0 = load_input0(coord, -1, -1);
    var s0_0_1 = load_input0(coord, 0, -1);
    var s0_0_2 = load_input0(coord, 1, -1);
    var s0_1_0 = load_input0(coord, -1, 0);
    var s0_1_1 = load_input0(coord, 0, 0);
    var s0_1_2 = load_input0(coord, 1, 0);
    var s0_2_0 = load_input0(coord, -1, 1);
    var s0_2_1 = load_input0(coord, 0, 1);
    var s0_2_2 = load_input0(coord, 1, 1);
    r0 += vec4<f32>(dot(s0_0_0, vec4<f32>(1.255e-01, 3.371e-03, 2.673e-04, 8.862e-02)), dot(s0_0_0, vec4<f32>(5.798e-02, 2.788e-03, 8.711e-04, -1.069e-02)), dot(s0_0_0, vec4<f32>(-1.163e-02, 1.468e-02, 3.817e-04, -1.059e-02)), dot(s0_0_0, vec4<f32>(-8.770e-03, 4.457e-03, -1.424e-07, -1.579e-02)));
    r0 += vec4<f32>(dot(s0_0_1, vec4<f32>(1.861e-01, 4.479e-02, -1.453e-03, -1.167e-01)), dot(s0_0_1, vec4<f32>(1.508e-01, 2.555e-02, 6.543e-03, 1.298e-01)), dot(s0_0_1, vec4<f32>(1.333e-03, 1.787e-01, -4.353e-04, -4.762e-02)), dot(s0_0_1, vec4<f32>(-4.843e-03, 3.182e-02, -8.008e-07, 2.935e-03)));
    r0 += vec4<f32>(dot(s0_0_2, vec4<f32>(-6.974e-03, -2.124e-01, 1.173e-03, -1.048e-02)), dot(s0_0_2, vec4<f32>(4.382e-02, -3.001e-01, -7.187e-03, 7.156e-02)), dot(s0_0_2, vec4<f32>(-7.400e-04, 1.984e-02, -1.022e-03, -2.708e-03)), dot(s0_0_2, vec4<f32>(-3.396e-03, 2.780e-01, -6.778e-04, -3.875e-02)));
    r0 += vec4<f32>(dot(s0_1_0, vec4<f32>(-1.577e-01, -6.336e-03, 2.277e-03, 1.170e-01)), dot(s0_1_0, vec4<f32>(1.250e-02, -3.293e-03, -1.022e-02, -1.107e-02)), dot(s0_1_0, vec4<f32>(-8.648e-02, 1.110e-03, -1.019e-03, 1.322e-01)), dot(s0_1_0, vec4<f32>(-4.689e-02, 2.097e-03, -3.308e-03, 2.385e-03)));
    r0 += vec4<f32>(dot(s0_1_1, vec4<f32>(-8.021e-02, 2.173e-01, -5.569e-01, -6.368e-02)), dot(s0_1_1, vec4<f32>(-6.038e-01, -4.296e-02, -1.812e-01, 5.282e-01)), dot(s0_1_1, vec4<f32>(4.326e-01, 1.675e-01, -9.005e-02, -8.165e-01)), dot(s0_1_1, vec4<f32>(-1.053e-01, 2.452e-02, 6.056e-02, 1.111e-01)));
    r0 += vec4<f32>(dot(s0_1_2, vec4<f32>(-1.173e-02, 1.665e-01, 3.799e-01, -7.982e-02)), dot(s0_1_2, vec4<f32>(1.275e-01, -1.548e-01, -6.418e-02, 1.027e-01)), dot(s0_1_2, vec4<f32>(4.014e-03, -7.352e-02, -2.039e-02, -2.271e-02)), dot(s0_1_2, vec4<f32>(2.144e-01, -7.022e-01, -2.607e-01, 6.812e-02)));
    r0 += vec4<f32>(dot(s0_2_0, vec4<f32>(2.949e-03, -6.587e-04, -1.238e-02, 1.998e-04)), dot(s0_2_0, vec4<f32>(2.134e-03, 1.055e-04, 9.397e-03, -1.396e-03)), dot(s0_2_0, vec4<f32>(-8.520e-02, -1.581e-02, 3.083e-03, 6.518e-02)), dot(s0_2_0, vec4<f32>(8.288e-03, -6.011e-03, 2.538e-03, 4.520e-03)));
    r0 += vec4<f32>(dot(s0_2_1, vec4<f32>(-9.190e-03, 5.656e-03, -1.432e-02, -4.086e-03)), dot(s0_2_1, vec4<f32>(1.922e-02, 9.584e-03, -3.629e-02, -2.335e-02)), dot(s0_2_1, vec4<f32>(-6.755e-02, 1.098e-02, 1.106e-01, 1.047e-01)), dot(s0_2_1, vec4<f32>(-1.704e-01, -2.932e-02, 1.470e-01, 1.373e-01)));
    r0 += vec4<f32>(dot(s0_2_2, vec4<f32>(7.299e-03, 2.891e-03, 8.160e-03, -1.123e-02)), dot(s0_2_2, vec4<f32>(6.259e-03, -2.629e-03, 6.618e-02, -1.263e-02)), dot(s0_2_2, vec4<f32>(-6.744e-03, 4.639e-02, 1.782e-01, -3.014e-02)), dot(s0_2_2, vec4<f32>(6.162e-03, 3.400e-02, 2.162e-01, 3.908e-02)));
    r0 += vec4<f32>(-2.727e-11, -1.608e-10, -1.877e-11, -2.711e-10);
    write_output_luma_value(base + vec2<i32>(0, 0), r0.x + sample_source_luma_for_output(base + vec2<i32>(0, 0)));
    write_output_luma_value(base + vec2<i32>(1, 0), r0.y + sample_source_luma_for_output(base + vec2<i32>(1, 0)));
    write_output_luma_value(base + vec2<i32>(0, 1), r0.z + sample_source_luma_for_output(base + vec2<i32>(0, 1)));
    write_output_luma_value(base + vec2<i32>(1, 1), r0.w + sample_source_luma_for_output(base + vec2<i32>(1, 1)));
}
